-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 22:05:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NTS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NTS` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema p
-- -----------------------------------------------------
USE `NTS` ;

-- -----------------------------------------------------
-- Table `NTS`.`Tipos_de_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Tipos_de_usuario` (
  `id_Tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Departamento` (
  `id_departamento` INT NOT NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Municipios` (
  `id_municipio` INT NOT NULL,
  `municipio` VARCHAR(45) NULL,
  `estado` INT NULL,
  `Departamento_id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_Ciudad_Departamento_idx` (`Departamento_id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Departamento`
    FOREIGN KEY (`Departamento_id_departamento`)
    REFERENCES `NTS`.`Departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nit_cliente` VARCHAR(45) NULL,
  `razon_social_cliente` VARCHAR(45) NULL,
  `direccion_cliente` VARCHAR(45) NULL,
  `telefono_cliente` VARCHAR(45) NULL,
  `email_cliente` VARCHAR(45) NULL,
  `Municipios_id_municipio` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_Gestores_Municipios1_idx` (`Municipios_id_municipio` ASC) VISIBLE,
  CONSTRAINT `fk_Gestores_Municipios1`
    FOREIGN KEY (`Municipios_id_municipio`)
    REFERENCES `NTS`.`Municipios` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL,
  `apellido_usuario` VARCHAR(45) NULL,
  `cedula_usuario` INT NULL,
  `telefono_usuario` VARCHAR(45) NULL,
  `email_usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `Tipos_de_usuario_id_Tipo_usuario` INT NOT NULL,
  `Clientes_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipos_de_usuario1_idx` (`Tipos_de_usuario_id_Tipo_usuario` ASC) VISIBLE,
  INDEX `fk_Usuarios_Clientes1_idx` (`Clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipos_de_usuario1`
    FOREIGN KEY (`Tipos_de_usuario_id_Tipo_usuario`)
    REFERENCES `NTS`.`Tipos_de_usuario` (`id_Tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Clientes1`
    FOREIGN KEY (`Clientes_id_cliente`)
    REFERENCES `NTS`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Bodega` (
  `id_bodega` INT NOT NULL AUTO_INCREMENT,
  `nombre_bodega` VARCHAR(45) NULL,
  `direccion_bodega` VARCHAR(45) NULL,
  `telefono_bodega` VARCHAR(45) NULL,
  `Municipios_id_municipio` INT NOT NULL,
  PRIMARY KEY (`id_bodega`),
  INDEX `fk_Bodega_Municipios1_idx` (`Municipios_id_municipio` ASC) VISIBLE,
  CONSTRAINT `fk_Bodega_Municipios1`
    FOREIGN KEY (`Municipios_id_municipio`)
    REFERENCES `NTS`.`Municipios` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Estante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Estante` (
  `id_estante` INT NOT NULL,
  `descripcion_estante` VARCHAR(45) NULL,
  `Bodega_id_bodega` INT NOT NULL,
  PRIMARY KEY (`id_estante`),
  INDEX `fk_Estante_Bodega1_idx` (`Bodega_id_bodega` ASC) VISIBLE,
  CONSTRAINT `fk_Estante_Bodega1`
    FOREIGN KEY (`Bodega_id_bodega`)
    REFERENCES `NTS`.`Bodega` (`id_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Cara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Cara` (
  `id_cara` INT NOT NULL,
  `descripcion_cara` VARCHAR(45) NULL,
  `Estante_id_estante` INT NOT NULL,
  PRIMARY KEY (`id_cara`),
  INDEX `fk_Cara_Estante1_idx` (`Estante_id_estante` ASC) VISIBLE,
  CONSTRAINT `fk_Cara_Estante1`
    FOREIGN KEY (`Estante_id_estante`)
    REFERENCES `NTS`.`Estante` (`id_estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Modulo` (
  `id_modulo` INT NOT NULL,
  `descripcion_modulo` VARCHAR(45) NULL,
  `Estante_id_estante` INT NOT NULL,
  `Cara_id_cara` INT NOT NULL,
  PRIMARY KEY (`id_modulo`),
  INDEX `fk_Modulo_Cara1_idx` (`Cara_id_cara` ASC) VISIBLE,
  INDEX `fk_Modulo_Estante1_idx` (`Estante_id_estante` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Cara1`
    FOREIGN KEY (`Cara_id_cara`)
    REFERENCES `NTS`.`Cara` (`id_cara`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modulo_Estante1`
    FOREIGN KEY (`Estante_id_estante`)
    REFERENCES `NTS`.`Estante` (`id_estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Piso` (
  `id_piso` INT NOT NULL,
  `descripcion_piso` VARCHAR(45) NULL,
  `Estante_id_estante` INT NOT NULL,
  `Cara_id_cara` INT NOT NULL,
  `Modulo_id_modulo` INT NOT NULL,
  PRIMARY KEY (`id_piso`),
  INDEX `fk_Piso_Modulo1_idx` (`Modulo_id_modulo` ASC) VISIBLE,
  INDEX `fk_Piso_Estante1_idx` (`Estante_id_estante` ASC) VISIBLE,
  INDEX `fk_Piso_Cara1_idx` (`Cara_id_cara` ASC) VISIBLE,
  CONSTRAINT `fk_Piso_Modulo1`
    FOREIGN KEY (`Modulo_id_modulo`)
    REFERENCES `NTS`.`Modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Estante1`
    FOREIGN KEY (`Estante_id_estante`)
    REFERENCES `NTS`.`Estante` (`id_estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Cara1`
    FOREIGN KEY (`Cara_id_cara`)
    REFERENCES `NTS`.`Cara` (`id_cara`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Entrepano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Entrepano` (
  `id_entrepano` INT NOT NULL,
  `descripcion_entrepano` VARCHAR(45) NULL,
  `Estante_id_estante` INT NOT NULL,
  `Cara_id_cara` INT NOT NULL,
  `Modulo_id_modulo` INT NOT NULL,
  `Piso_id_piso` INT NOT NULL,
  PRIMARY KEY (`id_entrepano`),
  INDEX `fk_Entrepano_Piso1_idx` (`Piso_id_piso` ASC) VISIBLE,
  INDEX `fk_Entrepano_Modulo1_idx` (`Modulo_id_modulo` ASC) VISIBLE,
  INDEX `fk_Entrepano_Cara1_idx` (`Cara_id_cara` ASC) VISIBLE,
  INDEX `fk_Entrepano_Estante1_idx` (`Estante_id_estante` ASC) VISIBLE,
  CONSTRAINT `fk_Entrepano_Piso1`
    FOREIGN KEY (`Piso_id_piso`)
    REFERENCES `NTS`.`Piso` (`id_piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrepano_Modulo1`
    FOREIGN KEY (`Modulo_id_modulo`)
    REFERENCES `NTS`.`Modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrepano_Cara1`
    FOREIGN KEY (`Cara_id_cara`)
    REFERENCES `NTS`.`Cara` (`id_cara`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrepano_Estante1`
    FOREIGN KEY (`Estante_id_estante`)
    REFERENCES `NTS`.`Estante` (`id_estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Ubicacion_caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Ubicacion_caja` (
  `id_ubicacion_caja` INT NOT NULL AUTO_INCREMENT,
  `ubicacion_X` VARCHAR(45) NULL,
  `ubicacion_Y` VARCHAR(45) NULL,
  `ubicacion_Z` VARCHAR(45) NULL,
  `estado_ubicacion` INT NULL,
  `Entrepano_id_entrepano` INT NOT NULL,
  PRIMARY KEY (`id_ubicacion_caja`),
  INDEX `fk_Ubicacion_caja_Entrepano1_idx` (`Entrepano_id_entrepano` ASC) VISIBLE,
  CONSTRAINT `fk_Ubicacion_caja_Entrepano1`
    FOREIGN KEY (`Entrepano_id_entrepano`)
    REFERENCES `NTS`.`Entrepano` (`id_entrepano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Estado_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Estado_item` (
  `id_estado_item` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_item` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Tipo_caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Tipo_caja` (
  `id_tipo_caja` INT NOT NULL,
  `nombre_tipo_caja` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_caja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Cajas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Cajas` (
  `id_caja` INT NOT NULL AUTO_INCREMENT,
  `nombre_caja` VARCHAR(45) NULL,
  `descripcion_caja` VARCHAR(45) NULL,
  `Ubicacion_caja_id_ubicacion_caja` INT NOT NULL,
  `Estado_item_id_estado_item` INT NOT NULL,
  `Tipo_caja_id_tipo_caja` INT NOT NULL,
  PRIMARY KEY (`id_caja`),
  INDEX `fk_Cajas_Ubicacion_caja1_idx` (`Ubicacion_caja_id_ubicacion_caja` ASC) VISIBLE,
  INDEX `fk_Cajas_Estado_item1_idx` (`Estado_item_id_estado_item` ASC) VISIBLE,
  INDEX `fk_Cajas_Tipo_caja1_idx` (`Tipo_caja_id_tipo_caja` ASC) VISIBLE,
  CONSTRAINT `fk_Cajas_Ubicacion_caja1`
    FOREIGN KEY (`Ubicacion_caja_id_ubicacion_caja`)
    REFERENCES `NTS`.`Ubicacion_caja` (`id_ubicacion_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajas_Estado_item1`
    FOREIGN KEY (`Estado_item_id_estado_item`)
    REFERENCES `NTS`.`Estado_item` (`id_estado_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajas_Tipo_caja1`
    FOREIGN KEY (`Tipo_caja_id_tipo_caja`)
    REFERENCES `NTS`.`Tipo_caja` (`id_tipo_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Tipo_de_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Tipo_de_prestamo` (
  `id_tipo_prestamo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_prestamo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_prestamo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Prioridad_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Prioridad_prestamo` (
  `id_prioridad` INT NOT NULL AUTO_INCREMENT,
  `nombre_prioridad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATE NULL,
  `Usuarios_id_usuario` INT NOT NULL,
  `Tipo_de_prestamo_id_tipo_prestamo` INT NOT NULL,
  `Prioridad_prestamo_id_prioridad` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_Prestamo_Usuarios1_idx` (`Usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_Prestamo_Tipo_de_prestamo1_idx` (`Tipo_de_prestamo_id_tipo_prestamo` ASC) VISIBLE,
  INDEX `fk_Prestamo_Prioridad_prestamo1_idx` (`Prioridad_prestamo_id_prioridad` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario`)
    REFERENCES `NTS`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Tipo_de_prestamo1`
    FOREIGN KEY (`Tipo_de_prestamo_id_tipo_prestamo`)
    REFERENCES `NTS`.`Tipo_de_prestamo` (`id_tipo_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Prioridad_prestamo1`
    FOREIGN KEY (`Prioridad_prestamo_id_prioridad`)
    REFERENCES `NTS`.`Prioridad_prestamo` (`id_prioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Cajas_has_Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Cajas_has_Prestamo` (
  `Cajas_id_caja` INT NOT NULL,
  `Prestamo_id_prestamo` INT NOT NULL,
  PRIMARY KEY (`Cajas_id_caja`, `Prestamo_id_prestamo`),
  INDEX `fk_Cajas_has_Prestamo_Prestamo1_idx` (`Prestamo_id_prestamo` ASC) VISIBLE,
  INDEX `fk_Cajas_has_Prestamo_Cajas1_idx` (`Cajas_id_caja` ASC) VISIBLE,
  CONSTRAINT `fk_Cajas_has_Prestamo_Cajas1`
    FOREIGN KEY (`Cajas_id_caja`)
    REFERENCES `NTS`.`Cajas` (`id_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajas_has_Prestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_id_prestamo`)
    REFERENCES `NTS`.`Prestamo` (`id_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Carpeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Carpeta` (
  `id_carpeta` INT NOT NULL AUTO_INCREMENT,
  `codigo_carpeta` VARCHAR(45) NULL,
  `Cajas_id_caja` INT NOT NULL,
  `Estado_item_id_estado_item` INT NOT NULL,
  PRIMARY KEY (`id_carpeta`),
  INDEX `fk_Carpeta_Cajas1_idx` (`Cajas_id_caja` ASC) VISIBLE,
  INDEX `fk_Carpeta_Estado_item1_idx` (`Estado_item_id_estado_item` ASC) VISIBLE,
  CONSTRAINT `fk_Carpeta_Cajas1`
    FOREIGN KEY (`Cajas_id_caja`)
    REFERENCES `NTS`.`Cajas` (`id_caja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carpeta_Estado_item1`
    FOREIGN KEY (`Estado_item_id_estado_item`)
    REFERENCES `NTS`.`Estado_item` (`id_estado_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NTS`.`Folio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NTS`.`Folio` (
  `id_folio` INT NOT NULL AUTO_INCREMENT,
  `codigo_folio` VARCHAR(45) NULL,
  `desc_folio` VARCHAR(45) NULL,
  `Carpeta_id_carpeta` INT NOT NULL,
  `Estado_item_id_estado_item` INT NOT NULL,
  PRIMARY KEY (`id_folio`),
  INDEX `fk_Folio_Carpeta1_idx` (`Carpeta_id_carpeta` ASC) VISIBLE,
  INDEX `fk_Folio_Estado_item1_idx` (`Estado_item_id_estado_item` ASC) VISIBLE,
  CONSTRAINT `fk_Folio_Carpeta1`
    FOREIGN KEY (`Carpeta_id_carpeta`)
    REFERENCES `NTS`.`Carpeta` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Folio_Estado_item1`
    FOREIGN KEY (`Estado_item_id_estado_item`)
    REFERENCES `NTS`.`Estado_item` (`id_estado_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
